version: '3'
services:
  backend:
    build: ./speechemotionrecognition_flask
    expose:
      - "10000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  frontend:
    build: ./speechemotionrec_frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://nginx/api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge