version: '3'
services:
  backend:
    build: ./speechemotionrecognition_flask
    ports:
      - "10000:10000"
    volumes:
      - ./speechemotionrecognition_flask:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./speechemotionrec_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./speechemotionrec_frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend